// playground/react-app/src/main.tsx
import { StrictMode } from "react"
import { createRoot } from "react-dom/client"
import { BrowserRouter, Route, Routes } from "react-router"
import { DemoPage } from "./demo/DemoPage"
import "./app.css"

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<DemoPage />} />
      </Routes>
    </BrowserRouter>
  </StrictMode>,
)

// playground/solid-app/src/index.tsx
/* @refresh reload */
import { render } from "solid-js/web"
import { Router, Route } from "@solidjs/router"
import { DemoPage } from "./demo/DemoPage"
import "./app.css"

render(
  () => (
    <Router>
      <Route path="/" component={DemoPage} />
    </Router>
  ),
  document.getElementById("root")!,
)
