// playground/react-app/src/components/Badge.tsx
import type { ReactNode } from "react"

export interface BadgeProps {
  /** Semantic color of the badge */
  tone?: "neutral" | "success" | "warning" | "danger"
  /** Render with a leading status dot */
  dot?: boolean
  children?: ReactNode
}

const tones: Record<string, string> = {
  neutral: "bg-zinc-100 text-zinc-700",
  success: "bg-emerald-100 text-emerald-800",
  warning: "bg-amber-100 text-amber-800",
  danger: "bg-red-100 text-red-800",
}

const dots: Record<string, string> = {
  neutral: "bg-zinc-400",
  success: "bg-emerald-500",
  warning: "bg-amber-500",
  danger: "bg-red-500",
}

/** Small status label for rows, cards, and headers. */
export function Badge({ tone = "neutral", dot, children }: BadgeProps) {
  return (
    <span
      className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-xs font-medium ${tones[tone]}`}
    >
      {dot && <span className={`size-1.5 rounded-full ${dots[tone]}`} />}
      {children}
    </span>
  )
}

// playground/vue-app/src/components/Badge.vue
<script setup lang="ts">
/** Small status label for rows, cards, and headers. */
interface Props {
  /** Colour role. */
  tone?: "default" | "success" | "warning" | "danger"
  /** Text inside the badge. */
  label?: string
}
const props = withDefaults(defineProps<Props>(), { tone: "default", label: "Badge" })

const tones: Record<string, string> = {
  default: "bg-zinc-100 text-zinc-700",
  success: "bg-emerald-50 text-emerald-700",
  warning: "bg-amber-50 text-amber-700",
  danger: "bg-red-50 text-red-700",
}
</script>

<template>
  <span
    :class="['inline-flex items-center rounded-full px-2.5 py-0.5 text-sm font-medium', tones[props.tone]]"
  >
    {{ props.label }}
  </span>
</template>
