// playground/vue-app/src/components/Card.vue
<script setup lang="ts">
/** Content container with an optional header. */
interface Props {
  /** Heading above the body. */
  title?: string
  /** Supporting line under the heading. */
  description?: string
  /** Body content; composed children serialize into the state URL. */
  children?: unknown
}
const props = withDefaults(defineProps<Props>(), {
  title: "Team settings",
  description: "Manage who has access to this workspace.",
})
</script>

<template>
  <div class="w-[380px] rounded-2xl border border-black/[0.08] bg-white p-6">
    <h3 class="text-base font-semibold text-zinc-900">{{ props.title }}</h3>
    <p class="mt-1 text-sm text-zinc-500">{{ props.description }}</p>
    <div class="mt-4"><slot /></div>
  </div>
</template>

// src/components/Card.tsx
import { Show, mergeProps, type JSX } from "solid-js"

export interface CardProps {
  /** Heading shown in the card header */
  title?: string
  /** Footer caption, typically metadata or a summary line */
  footer?: string
  /** Remove body padding for full-bleed content like tables */
  flush?: boolean
  children?: JSX.Element
}

/** Content container with optional header and footer. */
export function Card(props: CardProps) {
  const p = mergeProps({ flush: false }, props)
  return (
    <div class="w-80 overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-sm">
      <Show when={p.title}>
        <div class="border-b border-zinc-100 px-5 py-3.5">
          <h3 class="text-sm font-semibold text-zinc-900">{p.title}</h3>
        </div>
      </Show>
      <div class={p.flush ? "" : "px-5 py-4"}>{p.children}</div>
      <Show when={p.footer}>
        <div class="border-t border-zinc-100 bg-zinc-50 px-5 py-2.5 text-xs text-zinc-500">
          {p.footer}
        </div>
      </Show>
    </div>
  )
}
