// site/src/components/Button.tsx
import { mergeProps, splitProps, type JSX } from "solid-js"

export interface ButtonProps {
  /** Visual weight. Primary is the single page action. */
  variant?: "primary" | "secondary" | "ghost"
  /** Control height. */
  size?: "sm" | "md"
  /** The pre-review draft: sharp corners, cramped padding, flat press. */
  draft?: boolean
  /** Label text. */
  children?: JSX.Element
  onClick?: () => void
  href?: string
}

/** The page's only button. Every call to action on steerui.com is this component. */
export function Button(props: ButtonProps) {
  const merged = mergeProps({ variant: "primary" as const, size: "md" as const, draft: false }, props)
  const [, rest] = splitProps(merged, ["variant", "size", "draft", "children", "href"])

  const classes = () => {
    const base = "refines inline-flex items-center justify-center gap-2 font-medium select-none"
    const shape = merged.draft ? "rounded-[4px]" : "rounded-full"
    // Padding and type stay fixed in both states: refining a component must
    // never change its footprint, or everything around it jumps.
    const pad = merged.size === "sm" ? "px-4 py-1.5 text-[15px]" : "px-5 py-2.5 text-base"
    const skin =
      merged.variant === "primary"
        ? merged.draft
          ? "bg-zinc-900 text-white shadow-none"
          : "bg-zinc-900 text-white shadow-[0_1px_2px_rgba(0,0,0,0.12),0_6px_16px_rgba(0,0,0,0.14)] hover:bg-zinc-800"
        : merged.variant === "secondary"
          ? merged.draft
            ? "bg-white text-zinc-900 border border-zinc-400"
            : "bg-white text-zinc-900 border border-zinc-200/90 shadow-[0_1px_2px_rgba(0,0,0,0.04)] hover:border-zinc-300"
          : merged.draft
            ? "text-zinc-500"
            : "text-zinc-600 hover:text-zinc-900"
    return `${base} ${shape} ${pad} ${skin}`
  }

  return (
    <a class={classes()} href={props.href ?? "#"} {...rest}>
      {merged.children}
    </a>
  )
}

// playground/react-app/src/components/Button.tsx
import type { ReactNode } from "react"

export interface ButtonProps {
  /** Visual emphasis */
  variant?: "primary" | "secondary" | "ghost" | "destructive"
  /** Control height and padding */
  size?: "sm" | "md" | "lg"
  /** Prevent interaction */
  disabled?: boolean
  /** Replace label with a spinner while an action is in flight */
  loading?: boolean
  children?: ReactNode
  onClick?: () => void
}

const variants: Record<string, string> = {
  primary: "bg-zinc-900 text-white hover:bg-zinc-700",
  secondary: "bg-white text-zinc-900 border border-zinc-300 hover:border-zinc-500",
  ghost: "bg-transparent text-zinc-600 hover:text-zinc-900",
  destructive: "bg-red-600 text-white hover:bg-red-500",
}

const sizes: Record<string, string> = {
  sm: "h-8 px-3 text-sm",
  md: "h-10 px-4 text-sm",
  lg: "h-12 px-6 text-base",
}

/** The workhorse action trigger. */
export function Button({
  variant = "primary",
  size = "md",
  disabled,
  loading,
  children,
  onClick,
}: ButtonProps) {
  return (
    <button
      type="button"
      className={`inline-flex items-center justify-center gap-2 rounded-lg font-medium transition-colors disabled:opacity-40 disabled:pointer-events-none ${variants[variant]} ${sizes[size]}`}
      disabled={disabled || loading}
      onClick={() => onClick?.()}
    >
      {loading && (
        <span className="size-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
      )}
      {children}
    </button>
  )
}
