// src/adapters/react/mount-bench.tsx
import { StrictMode } from "react"
import { createRoot } from "react-dom/client"
import { BrowserRouter, Route, Routes } from "react-router"
import { SteerIndex } from "./SteerIndex"
import { SteerComponent } from "./SteerComponent"

/** Own document for /__steer. The host app never imports this. */
export function mountBench(): void {
  const el = document.getElementById("steer-root")
  if (!el) return
  createRoot(el).render(
    <StrictMode>
      <BrowserRouter>
        <Routes>
          <Route path="/__steer" element={<SteerIndex />} />
          <Route path="/__steer/:slug" element={<SteerComponent />} />
        </Routes>
      </BrowserRouter>
    </StrictMode>,
  )
}

// src/adapters/solid/mount-bench.tsx
import { render } from "solid-js/web"
import { Router, Route } from "@solidjs/router"
import { SteerIndex } from "./SteerIndex"
import { SteerComponent } from "./SteerComponent"

/** Own document for /__steer. The host app never imports this. */
export function mountBench(): void {
  const el = document.getElementById("steer-root")
  if (!el) return
  render(
    () => (
      <Router>
        <Route path="/__steer" component={SteerIndex} />
        <Route path="/__steer/:slug" component={SteerComponent} />
      </Router>
    ),
    el,
  )
}
