// playground/react-app/src/components/Badge.tsx
import type { ReactNode } from "react"

export interface BadgeProps {
  /** Semantic color of the badge */
  tone?: "neutral" | "success" | "warning" | "danger"
  /** Render with a leading status dot */
  dot?: boolean
  children?: ReactNode
}

const tones: Record<string, string> = {
  neutral: "bg-zinc-100 text-zinc-700",
  success: "bg-emerald-100 text-emerald-800",
  warning: "bg-amber-100 text-amber-800",
  danger: "bg-red-100 text-red-800",
}

const dots: Record<string, string> = {
  neutral: "bg-zinc-400",
  success: "bg-emerald-500",
  warning: "bg-amber-500",
  danger: "bg-red-500",
}

/** Small status label for rows, cards, and headers. */
export function Badge({ tone = "neutral", dot, children }: BadgeProps) {
  return (
    <span
      className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-xs font-medium ${tones[tone]}`}
    >
      {dot && <span className={`size-1.5 rounded-full ${dots[tone]}`} />}
      {children}
    </span>
  )
}

// site/src/components/Badge.tsx
import { mergeProps, type JSX } from "solid-js"

export interface BadgeProps {
  /** Who or what the badge speaks for. Human feedback is amber, agent indigo. */
  tone?: "neutral" | "human" | "agent"
  /** The pre-review draft: low contrast, boxy, oversized. */
  draft?: boolean
  children?: JSX.Element
}

/** A small status marker. Carries authorship colour wherever feedback appears. */
export function Badge(props: BadgeProps) {
  const merged = mergeProps({ tone: "neutral" as const, draft: false }, props)

  const classes = () => {
    const base = "refines inline-flex items-center gap-1.5 font-medium whitespace-nowrap"
    const shape = `px-2.5 py-0.5 text-[13px] ${merged.draft ? "rounded-[3px]" : "rounded-full"}`
    const skin =
      merged.tone === "human"
        ? merged.draft ? "bg-amber-50 text-amber-300 ring-1 ring-transparent" : "bg-amber-50 text-amber-700 ring-1 ring-amber-200/70"
        : merged.tone === "agent"
          ? merged.draft ? "bg-indigo-50 text-indigo-300 ring-1 ring-transparent" : "bg-indigo-50 text-indigo-700 ring-1 ring-indigo-200/70"
          : merged.draft ? "bg-zinc-100 text-zinc-400 ring-1 ring-transparent" : "bg-zinc-100 text-zinc-600 ring-1 ring-zinc-200/70"
    return `${base} ${shape} ${skin}`
  }

  return <span class={classes()}>{merged.children}</span>
}
