// playground/app/src/index.tsx
/* @refresh reload */
import { render } from "solid-js/web"
import { Router, Route } from "@solidjs/router"
import { DemoPage } from "./demo/DemoPage"
import { BenchIndex } from "../../../src/adapters/solid/BenchIndex"
import { BenchComponent } from "../../../src/adapters/solid/BenchComponent"
import "./bench"
import "./app.css"

render(
  () => (
    <Router>
      <Route path="/" component={DemoPage} />
      <Route path="/__bench" component={BenchIndex} />
      <Route path="/__bench/:slug" component={BenchComponent} />
    </Router>
  ),
  document.getElementById("root")!
)

// playground/react-app/src/main.tsx
import { StrictMode } from "react"
import { createRoot } from "react-dom/client"
import { BrowserRouter, Route, Routes } from "react-router"
import { DemoPage } from "./demo/DemoPage"
import { BenchIndex } from "../../../src/adapters/react/BenchIndex"
import { BenchComponent } from "../../../src/adapters/react/BenchComponent"
import "./bench"
import "./app.css"

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<DemoPage />} />
        <Route path="/__bench" element={<BenchIndex />} />
        <Route path="/__bench/:slug" element={<BenchComponent />} />
      </Routes>
    </BrowserRouter>
  </StrictMode>
)
